version: "2"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
  
  model-api:
    build:
      context: ../urbaton
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../urbaton

  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../server