version: "3"
services:
  frontend:
    depends_on: 
      - backend
    build:
      context: .
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      NODE_ENV: production
  
  backend:
    build:
      context: ../urbaton